### PR TITLE
Add Another MiStyle Icon

### PR DESCRIPTION
**Pull request by Lagrio**
# [skip ci] Add Another MiStyle Icon

## 介绍 / Description
Add Another MiStyle Icon

## 更改内容 / Types of Changes

- UI界面 User Interface

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，既不会破坏原有任何功能(或我可以解决)，也不会影响对旧版本的支持 I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

### CODE REVIEW

**Review by ketal178 — APPROVED** [review]

**Review by qwq233 — CHANGES_REQUESTED** [review]
不是你还打算加图标吗 还打算加更多玩意就挂着先把

**Comment by ketal178** [comment]
> 不是你还打算加图标吗 还打算加更多玩意就挂着先把

建议icon/default|new year|mi style

**Comment by Lagrio** [comment]
@ketal178 不加了

**Comment by qwq233** [comment]
@ketal178 感觉好麻烦 没必要

**Review by qwq233 — APPROVED** [review]

**Pull request merged**
