### PR TITLE
[skip ci]Update build.gradle

### PR DESCRIPTION
**Pull request by qwq233**
# Update build.gradle  

## 介绍 / Description
GitHub修改了image的ndk版本，导致无法正常ci build

## 更改内容 / Types of Changes

- [x] 修复 Bugfix

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，且不会破坏任何功能(或我可以解决) I have tested the changes and verified that they work and don't break anything (as well as I can manage).
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

### CODE REVIEW

**Review by NextAlone — APPROVED** [review]

**Comment by JasonKhew96** [comment]
image
记得上一个 ci 构建是爆炸了的，这里是改了的，可是 commit 去哪了我不知道（

**Comment by qwq233** [comment]
@JasonKhew96 是改过一次 最近github又把ndk改回去了

**Comment by JasonKhew96** [comment]
> @JasonKhew96 是改过一次 最近github又把ndk改回去了

找到了，直接 cherry pick
https://github.com/ferredoxin/QNotified/commit/095db3d2f4f84b9130211aeef231b971ae5c23c1

**Comment by qwq233** [comment]
@JasonKhew96 我没admin 没法直接push 直接修了快一些 主要是github ci出毛病导致所有pr都不能merge

**Comment by qwq233** [comment]
看来不用了hhh

**Pull request closed without merging**
