### PR TITLE
Add validator to button in SettingsActivity

### PR DESCRIPTION
**Pull request by NextAlone**
Signed-off-by: NextAlone <12210746+NextAlone@users.noreply.github.com>

# Add validator to button in SettingsActivity

## 更改内容 / Types of Changes

- 增强优化 Enhancement/optimization

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，既不会破坏原有任何功能(或我可以解决)，也不会影响对旧版本的支持 I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

### CODE REVIEW

**Comment by cinit** [comment]
@NextAlone 天上一块大石头砸到了我的头上

**Comment by cinit** [comment]
@cinit 看来我待会又要 resolve conflicts 了

**Review by singleNeuron — DISMISSED** [review]

**Review by qwq233 — DISMISSED** [review]

**Comment by NextAlone** [comment]
> @cinit 看来我待会又要 resolve conflicts 了

大喜

**Review by cinit — APPROVED** [review]

**Review by singleNeuron — DISMISSED** [review]

**Review by qwq233 — CHANGES_REQUESTED** [review]
This branch has conflicts that must be resolved

**Review by qwq233 — APPROVED** [review]

**Review by ketal178 — APPROVED** [review]

**Review by cinit — APPROVED** [review]

**Review by singleNeuron — APPROVED** [review]

**Pull request merged**
