### PR TITLE
Add strict mode check

### PR DESCRIPTION
**Pull request by cinit**
Signed-off-by: Null Idle <xenonhydride@gmail.com>

## 介绍
添加阻塞UI线程检测(仅在调试版本生效)

## 检查列表

- [x] Tested

### CODE REVIEW

**Review by NextAlone — APPROVED** [review]

**Review by singleNeuron — CHANGES_REQUESTED** [review]
你给recommand use啊，只block有个屁用，`XposedHelpers.findAndHookMethod(StrictCheckMode.class,"warnStrictModeIfUiThread",...)`警告

**Comment by NextAlone** [comment]
> 你给recommand use啊，只block有个屁用，`XposedHelpers.findAndHookMethod(StrictCheckMode.class,"warnStrictModeIfUiThread",...)`警告

指ui线程不要find class

**Comment by singleNeuron** [comment]
@NextAlone 你用协程重写吧

**Review by keta1 — APPROVED** [review]

**Comment by NextAlone** [comment]
显示不完整

**Comment by singleNeuron** [comment]
The pull request has been no activity for too long time

**Pull request closed without merging**
