### PR TITLE
Modify Build Status Badge

### PR DESCRIPTION
**Pull request by qwq233**
# Modify Build Status Badge

## 更改内容 / Types of Changes

- 文档 Documentation

## 由这个PR解决或关闭的Issues / Issues Fixed or Closed by This PR

-  

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，既不会破坏原有任何功能(或我可以解决)，也不会影响对旧版本的支持 I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

### CODE REVIEW

**Review by NextAlone — APPROVED** [review]
好耶

**Comment by singleNeuron** [comment]
@qwq233

**Review by singleNeuron — APPROVED** [review]

**Comment by Padcr** [comment]
Unsubscribe  退订------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;singleNeuron&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月6日(星期六) 下午3:47
收件人:&nbsp;&quot;ferredoxin/QNotified&quot;<QNotified@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [ferredoxin/QNotified] Modify Build Status Badge (#523)

**Comment by qwq233** [comment]
@Padcr ?

**Review by ketal178 — APPROVED** [review]

**Pull request merged**
