### PR TITLE
Fix invokeOriginalMethod NPE if not hooked in Epic

### PR DESCRIPTION
**Pull request by cinit**
Signed-off-by: Null Idle <xenonhydride@gmail.com>

## 更改内容 / Types of Changes
- 修复 Bugfix

## 检查列表 / Checklist
- [ ] NOT TESTED BECAUSE I DO NOT HAVE TAICHI-EPIC ENVIRONMENT

### CODE REVIEW

**Review by ketal178 — APPROVED** [review]

**Comment by mis1042** [comment]
qwq球球快Merge吧

**Review by qwq233 — APPROVED** [review]

**Comment by mis1042** [comment]
好耶,开始构建ing
Nice,Let me bulid

**Comment by qwq233** [comment]
@mis1042 等ci不就好了= =

**Comment by mis1042** [comment]
CI估计要等亿小时

**Pull request merged**
