### PR TITLE
Update NA Utils with Xposed API

### PR DESCRIPTION
**Pull request by NextAlone**
Signed-off-by: NextAlone <12210746+NextAlone@users.noreply.github.com>

# Update NA Utils with Xposed API

## 更改内容 / Types of Changes

- 增强优化 Enhancement/optimization

## 检查列表 / Checklist

- [x] 我的代码符合本仓库的代码规范 My code follows the code style of this project
- [x] 我已经测试了这些更改，它们可以正常工作，既不会破坏原有任何功能(或我可以解决)，也不会影响对旧版本的支持 I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] 我已合并了对后续工作无意义的commit并确认不会对后续维护造成困扰 I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

### CODE REVIEW

**Review by huajijam — APPROVED** [review]
好耶

**Review by singleNeuron — APPROVED** [review]

**Comment by singleNeuron** [comment]
好耶

**Review by ketal178 — CHANGES_REQUESTED** [review]
你把判断搞了，功能开关不会实时生效

**Review by cinit — DISMISSED** [review]
You developer should keep your own faith.

**Review by ketal178 — APPROVED** [review]

**Review by cinit — APPROVED** [review]

**Review by singleNeuron — APPROVED** [review]
先过了，但是重构后框架一定要统一提供什么黑名单什么isEnable的处理，不要让各个模块自己wrapper

**Pull request merged**
